# Generated by Django 4.2.4 on 2023-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='contributer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
